

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR


spring:
  datasources:
    url: 'jdbc:h2:mem:test'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
